
vault_url: "https://vault.dev.playsoft.io:8200/"
vault_mount: "kv-dev"
vault_token: "{{ lookup('env', 'VAULT_TOKEN') }}"

# JumpServer — URL et password récupérés depuis Vault
jumpserver_admin_user: "admin"

# Utilisateur admin système — password récupéré depuis Vault
admin_user:
  name: "admin-user"
  username: "aymen-tangara"
  email: "aymen@example.com"

# Utilisateur DevOps — password récupéré depuis Vault
devops_user:
  name: "devops-user"
  username: "chaima-chaabeni"
  email: "chaima@example.com"

# Serveur public — ip et ssh_key_path récupérés depuis Vault
public_server:
  name: "public-server-chaima"
  internal_ip: "10.40.0.2"
  account_username: "root"

# Serveur privé — ip et ssh_key_path récupérés depuis Vault
private_server:
  name: "server-private-chaima"
  account_username: "root"

# Configuration d'autorisation utilisateur
user_authorization:
  target_username: "chaima-chaabeni"
  assets_names:
    - "server-private-chaima"
