---
jumpserver_url: "http://ip"
jumpserver_admin_user: "user-name"
jumpserver_admin_password: "password"

admin_user:
  name: "admin-user"
  username: "aymen-tangara"
  email: "aymen@example.com"
  password: "password"

devops_user:
  name: "devops-user"
  username: "chaima-chaabeni"
  email: "chaima@example.com"
  password: "password"

# Configuration serveur public
public_server:
  name: "name"
  ip: "ip-public"
  internal_ip: "ip-privat"
  account_username: "name"
  ssh_private_key_path: "sshkey"

# Configuration serveur privé
private_server:
  name: "private-server-chaima"
  ip: "ip-privat"
  account_username: "name"
  ssh_private_key_path: "sshkey"

# Configuration d'autorisation utilisateur
user_authorization:
  target_username: "chaima-chaabeni"
  assets_names:
    - "private-server-chaima"
