#cloud-config
packages:
  - ifupdown
package_update: true
#package_upgrade: true
runcmd:
  - |
    cat <<'EOF' >> /etc/systemd/network/10-enp7s0.network
    [Match]
    Name=enp7s0
    
    [Network]
    DHCP=yes
    #Gateway=10.0.0.1
    Gateway=${gateway_ip}
    EOF
    sudo sed -i 's/^#DNS=/DNS=8.8.8.8/' /etc/systemd/resolved.conf
  - reboot