#cloud-config
package_update: true
package_upgrade: true

packages:
  - docker.io
  - curl
  - git
  - python3-pip
  - libffi-dev
  - libssl-dev
  

write_files:
  - path: /etc/systemd/network/10-enp7s0.network
    content: |
      [Match]
      Name=enp7s0

      [Network]
      DHCP=yes
      Gateway=10.40.0.1

  - path: /etc/systemd/resolved.conf
    content: |
      [Resolve]
      DNS=185.12.64.2 185.12.64.1
      FallbackDNS=8.8.8.8

runcmd:
  # Redémarrer le réseau pour appliquer la gateway
  - systemctl restart systemd-networkd
  - systemctl restart systemd-resolved
  - sleep 5

  # Docker
  - systemctl enable docker
  - systemctl start docker
  - sleep 10

  # Installation JumpServer (mode rapide officiel)
  - curl -sSL https://github.com/jumpserver/jumpserver/releases/latest/download/quick_start.sh -o /tmp/jumpserver.sh
  - chmod +x /tmp/jumpserver.sh
  - bash /tmp/jumpserver.sh > /var/log/jumpserver-install.log 2>&1

  # Nettoyage
  - apt remove -y hc-utils || true

  - reboot
